Feat: Vertex AI via Rest
kgmedia-data/gaia pull request #6
Opened 2024-11-06 09:25 UTC by anwarfarihin

2024-11-11 01:51 UTC, lastcoala requested changes

2024-11-11 01:51 UTC, lastcoala commented on pkg/ml/summary_vertex.go
> +	SYSTEM_INSTRUCTION := "You are a tools for summarization of title of news articles."
Coba dibikin si VertexRestModelnya itu jadi kayak builder di Gorm atau di https://github.com/kgmedia-data/rec-core-v2/blob/main/internal/base/vector/redis_search.go atau kayak yang si Library Go nya vertex

Misalnya jadi kayak  `s.Model("gemini-1.5-flash-002").Temperature(1).Schema(xxxx).Instruct(xxxx).Prompt(xxxx)`

2024-11-11 01:52 UTC, lastcoala requested changes

2024-11-11 01:52 UTC, lastcoala commented on pkg/ml/config/config_summary.json
sama kalo bisa gk pake json2 ini lagi.

2024-11-18 04:52 UTC, lastcoala requested changes

2024-11-18 04:52 UTC, lastcoala commented on pkg/ml/summary_vertex.go
> +		AddLabels(map[string]string{
labels nya ini jangan di hardcode kali, taro di parameter constructor nya

2024-11-18 04:52 UTC, lastcoala commented on pkg/ml/summary_vertex.go
> +	resp, err := s.vertex.request.
di sini nya harusnya ndak berhubungan dengan Resty / requests nya secara langsung. Sama kayak nge marshal json, ngecek status code dll. Itu harusnya udah di abstraksi sama si vertex.go nya.

2024-11-19 04:59 UTC, anwarfarihin commented on pkg/ml/summary_vertex.go
> +	resp, err := s.vertex.request.
kalau sekarang udah sesuai belum mas? soalnya nanti tiap tipe model nya bakal punya structure output yang beda2 (kaya `ml.Summary[]`, atau RAG) gitu2, jadi harus di implement ulang di subclass `VertexRest`nya

2024-11-25 01:40 UTC, lastcoala approved these changes

2024-11-25 03:34 UTC, merged