feat: GCP logging
kgmedia-data/gaia pull request #7
Opened 2024-11-14 05:38 UTC by taufanbudiman

additinal ENV
- GCP_PROJECT_ID
- GCP_LOG_NAME

2024-11-14 08:43 UTC, lastcoala reviewed
Coba tambahin juga contoh cara ngelognya di `sample` . Terus buat configurasi lognya kayak projectid, logname, sama label2 nya coba ditambahin di config.go nya buat contoh.

2024-11-14 08:43 UTC, lastcoala commented on sample/internal/app/app.go
> +	pubChanGcpLogger := pub.NewChanPublisher(gcpLogChan)
yang 2 line ini masukin di CreateLoggerStream aja biar dia buat nya cuman pas handler nya ada aja

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +		insertIntoGCP = reflect.ValueOf(entry.Data["insertIntoGCP"]).Bool()
"insertIntoGCP" , kepanjangan kayaknya. "gcp" aja

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +		logName: os.Getenv("GCP_LOG_NAME"),
logName nya dijadiin parameter di NewGCPProcessor nya aja

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	projectID := os.Getenv("GCP_PROJECT_ID")
ini juga dari parameter di NewGCPProcessor nya aja

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	client, err := logging.NewClient(ctx, projectID)
ini mesti selalu diinitiate disini? gk sekali aja dk contructor nya?

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	logger := client.Logger(p.logName)
yang ini juga

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	if err := client.Close(); err != nil {
ini apakah harus selalau di close habis nge-log?

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	logName string
coba tambahin attribute `labels` yang tipenya map[string]string yang nantinya selalu dimasukin pas nge log ke GCP nya

2024-11-14 08:43 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	logName string
masukinnya lewat constructor nya

2024-11-15 00:15 UTC, taufanbudiman commented on pkg/log/gcp_log.go
> +	if err := client.Close(); err != nil {
kalau ini kemarin lihat dari docs ini sih Mas.. https://cloud.google.com/logging/docs/reference/libraries#client-libraries-usage-go, tapi kalau ga close pun dia tetep masuk

2024-11-15 00:25 UTC, taufanbudiman commented on pkg/log/gcp_log.go
> +	if err := client.Close(); err != nil {
apa tidak usa di close Mas?

2024-11-15 00:39 UTC, taufanbudiman commented on pkg/log/gcp_log.go
> +	logName string
apakah nanti attribute `labels` ini dikirim ke log Mas?
contoh seperti gambar
![image](https://github.com/user-attachments/assets/9dfef947-5adf-450d-a8bc-d138663a6e8e)

tapi pemanggilan lewat constructor seperti ini?
```go
logProc := gcp_log.NewGCPProcessor(
	os.Getenv("GCP_LOG_NAME"),
	os.Getenv("GCP_PROJECT_ID"),
	map[string]string{
		"log": "via stream",
	},
)
```

2024-11-15 00:46 UTC, taufanbudiman commented
> Coba tambahin juga contoh cara ngelognya di `sample` . Terus buat configurasi lognya kayak projectid, logname, sama label2 nya coba ditambahin di config.go nya buat contoh.

kalau di letakkan di `config.go` brarti tidak perlu pake `os.Getenv` ya Mas?

2024-11-18 01:26 UTC, lastcoala requested changes

2024-11-18 01:26 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	logName string
iya betul

2024-11-18 01:26 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	if err := client.Close(); err != nil {
iya tidak usah di close

2024-11-18 01:59 UTC, taufanbudiman commented on pkg/log/gcp_log.go
> +	logName string
untuk label ini mau di isi apa Mas ketika processor dipanggil?? manggil config lagi atau isi default seperti diatas?

2024-11-18 03:59 UTC, lastcoala requested changes

2024-11-18 03:59 UTC, lastcoala commented on sample/config/config.go
> +	GcpLog GcpLog       `mapstructure:"gcp_log"`
`mapstructure` nya dibikin `camelCase` aja, jadi `gcpLog`

2024-11-18 03:59 UTC, lastcoala commented on sample/config/config.go
> +	GcpLog GcpLog       `mapstructure:"gcp_log"`
yang lain juga

2024-11-18 03:59 UTC, lastcoala commented on sample/config/config.yaml
> +  log_name: "gia"
harusnya `gaia`

2024-11-18 03:59 UTC, lastcoala commented on sample/config/config.yaml
> +    project: "gaia-kgdata-aiml"
ini `gaia` aja

2024-11-18 03:59 UTC, lastcoala commented on pkg/log/gcp_log.go
> +		err := h.pub.Publish(msg.Message[string]{Data: entry.Message, Attribute: attr})
Di `entry` itu kan ada `Fields` , semua yang di `Fields` itu dimasukin ke `attr` aja

2024-11-18 03:59 UTC, lastcoala commented on pkg/log/gcp_log.go
> +	payload := map[string]any{
tambahin attribute `fields` kali yang isinya itu dari `message.Attr`

2024-11-18 04:47 UTC, lastcoala approved these changes

2024-11-18 07:19 UTC, merged